### ISSUE TITLE
E713  Cannot use empty key for Dictionary

### ISSUE THREAD

**Issue by lilijreey** [jalcine/cmake.vim#61]
Error detected while processing function cmake#augroup#on_vim_enter..cmake#targe
ts#cache:
line   13:
E713: Cannot use empty key for Dictionary
The function call cmake#targets#cache() throw this error.
I have been commented this call

**Comment by jalcine** [comment]
What was the file path of the buffer that this occured under?

**Comment by jalcine** [comment]
I see a potential problem in (`cmake#targets#cache()`)[https://github.com/jalcine/cmake.vim/blob/develop/autoload/cmake/targets.vim#L204-L210] and I've patched it in #63. Do you mind getting the project at that tree and trying the code out? It'd help even more if you mentioned what you were doing when you got to this error.

**Comment by jalcine** [comment]
@lilijreey: If you checkout the `develop` branch and try it out; it should work OK for you now. I'm still working on improving the test suite so I can check bugs like this in the future.

**Comment by jalcine** [comment]
Going to close this issue since the visible problem was fixed in #64.

**Comment by lilijreey** [comment]
thanks
